ALL_FILES <- list.files("./data/")
ALL_FILES <- ALL_FILES[!grepl("temp", ALL_FILES)]

ui <- fluidPage(
  titlePanel("Как распространяется нефть?"),
    sidebarPanel(
      numericInput(inputId = "time",
                   label = "Момент времени",
                   value = 1,
                   min = 1,
                   max = 1001),
      checkboxInput(inputId = "predictPast",
                    label = "Предсказывать прошлое",
                    value = FALSE),
      checkboxInput(inputId = "useLand",
                    label = "Учитывать сушу",
                    value = TRUE),
      checkboxInput(inputId = "autoDetection",
                    label = "Автоматическая детекция",
                    value = TRUE),
      numericInput(inputId = "velocity1",
                   label = "Скорость ветра по горизонтали (в м/с)",
                   value = 1),
      numericInput(inputId = "velocity2",
                   label = "Скорость ветра по вертикали (в м/с)",
                   value = 1),
      numericInput(inputId = "water_temperature",
                   label = "Температура воды (в градусах Цельсия)",
                   value = 22),
      numericInput(inputId = "granularity_level",
                   label = "Гранулярность (в клетках)",
                   value = 10,
                   min = 1,
                   max = 100),
      numericInput(inputId = "T_max",
                   label = "Максимальное время предсказания (в часах)",
                   value = 100,
                   min = 1,
                   max = 1001),
      numericInput(inputId = "step",
                   label = "Временной шаг дискретизации (в часах)",
                   value = 1,
                   min = 1,
                   max = 500),
      selectInput(inputId = "method",
                  label = "Метод решения системы ОДУ",
                  selected = "adams",
                  choices = c("lsodes", "euler", "rk4", "ode23", "ode45", "adams", "iteration")),
      selectInput(inputId = "data_file",
                  label = "Файл картинки",
                  selected = "wakasho_5230_2910.png",
                  choices = ALL_FILES[grepl("png", ALL_FILES)]),
      selectInput(inputId = "meteo_file",
                  label = "Файл метео данных",
                  selected = "scenario_meteo_data.csv",
                  choices = ALL_FILES[grepl("csv", ALL_FILES) &
                                      grepl("scenario", ALL_FILES)]),
      numericInput(inputId = "wind_coefficient",
                   label = "Коэффициент ветра",
                   value = 0.03),
      dateInput(inputId = "scenario_date",
                label = "Дата начала сценария",
                value = "2020-08-11"),
      checkboxInput(inputId = "useEmulsification",
                    label = "Учитывать эмульсию?",
                    value = TRUE),
      selectInput(inputId = "typeOfOil",
                  label = "Тип нефти",
                  selected = "лёгкая",
                  choices = c("лёгкая", "тяжёлая")),
      checkboxInput(inputId = "useEvaporation",
                    label = "Учитывать испарение?",
                    value = TRUE),
      numericInput(inputId = "massTransferRate",
                   label = "Коэффициент переноса массы",
                   value = 0.04),
      numericInput(inputId = "schmidtNumber",
                   label = "Число Шмидта",
                   value = 850),
      numericInput(inputId = "evaporation_r",
                   label = "Эмпирический показатель",
                   value = 0.33),
      checkboxInput(inputId = "useWaves",
                    label = "Учитывать волны?",
                    value = TRUE),
      checkboxInput(inputId = "useCurrents",
                    label = "Учитывать течения?",
                    value = TRUE),
      checkboxInput(inputId = "use3DModel",
                    label = "Использовать трёхмерную модель?",
                    value = FALSE),
      numericInput(inputId = "viscosity",
                   label = "Вязкость",
                   value = 2.86),
      numericInput(inputId = "rho_oil",
                   label = "Плотность нефти",
                   value = 900),
      numericInput(inputId = "diam_oil",
                   label = "Диаметр капель нефти",
                   value = 40)
    ),
    mainPanel(
      tabsetPanel(
        tabPanel(
          "Распространение нефти",
          plotOutput(outputId = "oilPlot", width = "100%", height = "1000px")
        ),
        tabPanel(
          "Сценарий распространения нефти",
          plotOutput(outputId = "oilPlot2", width = "100%", height = "1000px")
          )
      )
    )
)